### ISSUE TITLE
Todo List 2020-11-23

### ISSUE THREAD

**Issue by nicewook** [nicewook/gvm#11]
Todo list

- [x] align listall result and display as green installed version
  - [x] align
  - [x] display green for installed, red for using
  - [x] exception for the system
- [ ] readme reinforce
- [x] fmtV is not working sometimes: gvm listall
- [x] gvm use without argument - show current using version
- [ ] gvm install the latest
- [ ] gvm use the latest
- [ ] bugfix 
  - [ ] install not working at once
  - [x] gvm install error (uninstall okay)

**Comment by nicewook** [comment]
refined at https://github.com/nicewook/gvm/issues/12
