### ISSUE TITLE
Todo List 2020-11-27

### ISSUE THREAD

**Issue by nicewook** [nicewook/gvm#12]
## Todo list

- [ ] readme reinforce
  - [ ] explain on each cmd
  - [ ] usage on each cmd at README.md
- [ ] `fmt`, `fmtV` management - more clear, minimal print, add color
- [ ] latest option
  - [ ] gvm install latest
  - [ ] gvm use latest
- [x] list shows currently using version as red
- [ ] depense code for no argument of each command
- [ ] -d option for `use`
  - [ ] use version for only this directory
  - [ ] save it to viper config https://gist.github.com/nicewook/e349bf1500a589f25e06d26bc87a62a0
- [ ] bugfix
  - [x] install not working at once. check sync - may fixed
  - [x] list is not properly working at home pc
  - [ ] gvm install should be atomic - so prepare all and if failed rollback

**Comment by nicewook** [comment]
## install process

1. check the current go.exe file location and rename-to-be
2. check the next go<version>.exe file name and location 
3. rename current go.exe - but prepare for rollback
4. copy and rename next go<version>.exe file

if any failure, then rollback to original

**Comment by nicewook** [comment]
## summarize the source code of the dl

alreay analysis, so need to summarize
https://go.googlesource.com/dl
