### ISSUE TITLE
To-do list 2020-12-03

### ISSUE THREAD

**Issue by nicewook** [nicewook/gvm#13]
## To-do list for version 0.0.1

- [ ] readme essential
  - [x] general explanantion 
  - [x] how to install 
  - [x] explain on each cmd
  - [x] example code of each cmd
  - [ ] add gif files
- [ ] cobra cmd help for each cmd
- [ ] `fmt`, `fmtV` properly
- [ ] argument management of each command - no, one, many argements
- [ ] analyse code of https://go.googlesource.com/dl and save markdown file in directory `anaysis`
- [ ] use command more safely. prepare all and do change using version
  - [ ] if err, then rollback. gvm install should be atomic - so prepare all and if failed rollback
```
check the current go.exe file location and rename-to-be
check the next go.exe file name and location
rename current go.exe - but prepare for rollback
copy and rename next go.exe file
if any failure, then rollback to original
```

## Feature for future someday
- [ ] latest option
  - [ ] gvm install latest
  - [ ] gvm use latest
- [ ] -d option for `use`
  - [ ] use version for only this directory
  - [ ] save it to viper config https://gist.github.com/nicewook/e349bf1500a589f25e06d26bc87a62a0
  - [ ] it might be hard to work in powershell. it will not run pwd go.exe file

## Check later the feature of the reference `gvm` package
- [ ] implode
- [ ] linkthis
- [ ] alias
- [ ] pkgset
- [ ] pkgenv

**Comment by nicewook** [comment]
## Clean up for each cmd
- [x] root.go 2020-12-03
