### ISSUE TITLE
To-do list 2020-12-15

### ISSUE THREAD

**Issue by nicewook** [nicewook/gvm#15]
## General to-do list
- [ ] argument number management
  - [ ] limit argument number for command. ex) use == 1
  - [ ] no argument displays help
- [ ] Test code for each command
- [ ] add .gif files for the README.md. use `ScreenToGif` 
- [ ] analyse code of https://go.googlesource.com/dl and save markdown file in directory anaysis

## Enhancement
- [ ] install command
  - [ ] validate arguments (just like uninstall)
- [ ] use command
  - [ ] prepare everything and execute the changing using version more safely
  - [ ]  if err, then rollback. gvm install should be atomic - so prepare all and if failed rollback
```check the current go.exe file location and rename-to-be
check the next go.exe file name and location
rename current go.exe - but prepare for rollback
copy and rename next go.exe file
if any failure, then rollback to original
```

## Bug-fix
