### ISSUE TITLE
use command implement

### ISSUE THREAD

**Issue by nicewook** [nicewook/gvm#2]
### Todo list for "use" command

- [ ] copy wanted version `go` file to `go.exe`
- [ ] when we change to another version, we can remove `go.exe` or if no `go<version>.exe`, then rename as `go<version>.exe`

### Todo list for general

- [ ] log with file, line information
